services:
  - type: web
    name: beatdrop
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
